# Breaking change was removing the bit timing sections from hal::can::settings,
# now it is just baud_rate.
name: ðŸš€ Deploy 4.3.0

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      compiler: gcc
      version: 4.3.0
      arch: x86_64
      compiler_version: 12.3
      compiler_package: ""
      os: Linux
    secrets: inherit
